application: dy-hrd2 
version: 1
runtime: python
api_version: 1

handlers:
- url: /style
  static_dir: style

- url: /images
  static_dir: images

- url: /manage.*
  script: manage.py
  login: admin

- url: /.*
  script: index.py

builtins:
- remote_api: on

